export const SET_CURRENT_USER='SET_CURRENT_USER';
export const LOGOUT_USER='LOGOUT_USER';
export const SET_CURRENT_SOCKET='SET_CURRENT_SOCKET';
export const NEW_MESSAGE='NEW_MESSAGE';
export const GET_MESSAGE='GET_MESSAGE';
export const CONNECTED_USERS='CONNECTED_USERS';